### ISSUE TITLE
Great ,but  cant  login

### ISSUE THREAD

**Issue by helloCheng09** [unclezs/vue-admin-template-custom#3]
![123](https://user-images.githubusercontent.com/41097785/82976817-b8e39700-a012-11ea-9a3c-879ee82b4c57.png)

api: 
http://localhost:9529/auth/login

error msg:  
 Proxy error: Could not proxy request /auth/login from localhost:9529 to http://localhost:8654/ (ECONNREFUSED).

**Comment by unclezs** [comment]
配合服务端一起使用
